### ISSUE TITLE
bower install ->  bower ECONFLICT Unable to find suitable version for angular

### ISSUE THREAD

**Issue by zanjs** [theunexpected1/interactive#76]
$ bower install
bower angular#^1.3.x            cached git://github.com/angular/bower-angular.git#1.4.7
bower angular#^1.3.x          validate 1.4.7 against git://github.com/angular/bower-angular.git#^1.3.x
bower angular-animate#~1.3.x    cached git://github.com/angular/bower-angular-animate.git#1.3.20
bower angular-animate#~1.3.x  validate 1.3.20 against git://github.com/angular/bower-angular-animate.git#~1.3.x
bower ui-router#~0.2.15         cached git://github.com/angular-ui/ui-router.git#0.2.15
bower ui-router#~0.2.15       validate 0.2.15 against git://github.com/angular-ui/ui-router.git#~0.2.15
bower socket.io-client#~1.3.5   cached git://github.com/LearnBoost/socket.io-client.git#1.3.7
bower socket.io-client#~1.3.5 validate 1.3.7 against git://github.com/LearnBoost/socket.io-client.git#~1.3.5
bower angular-material#~0.9.4   cached git://github.com/angular/bower-material.git#0.9.8
bower angular-material#~0.9.4 validate 0.9.8 against git://github.com/angular/bower-material.git#~0.9.4
bower lodash#~3.9.2             cached git://github.com/lodash/lodash.git#3.9.3
bower lodash#~3.9.2           validate 3.9.3 against git://github.com/lodash/lodash.git#~3.9.2
bower jquery#~2.1.4             cached git://github.com/jquery/jquery.git#2.1.4
bower jquery#~2.1.4           validate 2.1.4 against git://github.com/jquery/jquery.git#~2.1.4
bower angular#>= 1.0.8          cached git://github.com/angular/bower-angular.git#1.4.7
bower angular#>= 1.0.8        validate 1.4.7 against git://github.com/angular/bower-angular.git#>= 1.0.8
bower angular-animate#^1.3.0 || >1.4.0-beta.0           cached git://github.com/angular/bower-angular-animate.git#1.4.7
bower angular-animate#^1.3.0 || >1.4.0-beta.0         validate 1.4.7 against git://github.com/angular/bower-angular-animate.git#^1.3.0 || >1.4.0-beta.0
bower angular#1.3.20                                    cached git://github.com/angular/bower-angular.git#1.3.20
bower angular#1.3.20                                  validate 1.3.20 against git://github.com/angular/bower-angular.git#1.3.20
bower angular-aria#^1.3.15 || >1.4.0-beta.0             cached git://github.com/angular/bower-angular-aria.git#1.4.7
bower angular-aria#^1.3.15 || >1.4.0-beta.0           validate 1.4.7 against git://github.com/angular/bower-angular-aria.git#^1.3.15 || >1.4.0-beta.0
bower                                                ECONFLICT Unable to find suitable version for angular

**Comment by theunexpected1** [comment]
Thanks for reporting this @zanjs, this is fixed now.
Cheers
